# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.CharField(blank=True, max_length=100, verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='topics', verbose_name='image')),
                ('likes', models.IntegerField(default=0)),
                ('users_likes', models.ManyToManyField(blank=True, related_name='topics_liked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['title'],
            },
        ),
    ]
