# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 10:13
from __future__ import unicode_literals

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(blank=True, help_text='Tell us about yourself in 140 characters.', max_length=140, verbose_name='about')),
                ('avatar', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=accounts.models.user_avatar_path, verbose_name='avatar')),
                ('email_confirmed', models.BooleanField(default=False, help_text="Determine if the User's email has been confirmed.", verbose_name='email confirmed?')),
                ('verified_account', models.BooleanField(default=False, verbose_name='verified account?')),
                ('website', models.URLField(blank=True, help_text='Begin your URL with http:// or https://', null=True, verbose_name='website')),
                ('location', models.CharField(blank=True, max_length=30, null=True, verbose_name='location')),
                ('favorite_club', models.CharField(blank=True, max_length=40, null=True, verbose_name='favorite club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
    ]
